# Site Configuration
baseURL = "https://project-drasi-docs.azurewebsites.net/"
title = "Project Drasi"
theme = "docsy"

# Attribution
author = "Azure Incubations"
copyright = "Copyright Â© 2023, Microsoft; all rights reserved."

# Language Configuration
languageCode = "en"
DefaultContentLanguage = "en"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
# Top Nav Bar
[[menu.main]]
    name = "SUPPORT"
    weight = 10
    url = "/support"
[[menu.main]]
    name = "CODE"
    weight = 20
    url = "https://dev.azure.com/azure-octo/Incubations/_git/ReactiveGraph?path=%2F&version=GBdevelop&_a=contents"

[module]
  [module.hugoVersion]
    extended = true